"""PC persistence and transport only; all new terrain is generated by the MCU."""
import json
import os
from pathlib import Path
import struct

HEIGHT = 128
SIZE = 16 * 16 * HEIGHT
LIMIT = 62500
STATE_COUNT = len(json.loads((Path(__file__).parent / 'data/states.json').read_text())['states'])


def atomic_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix('.tmp')
    with temporary.open('w', encoding='utf-8') as stream:
        json.dump(value, stream, separators=(',', ':'))
        stream.flush()
        os.fsync(stream.fileno())
    temporary.replace(path)


class ChunkStore:
    def __init__(self, root):
        self.root = Path(root)
        metadata = self.root / 'chunks-v1' / 'world.json'
        if metadata.exists():
            self.meta = json.loads(metadata.read_text())
            if self.meta.get('generator') != 1 or self.meta.get('height') != HEIGHT:
                raise ValueError('Unsupported chunk world format')
        else:
            self.meta = {'generator': 1, 'height': HEIGHT, 'seed': 0x4d435246}
            legacy = self.root / 'blocks.bin'
            if legacy.exists():
                data = legacy.read_bytes()
                if len(data) != 32768 or any(v == 255 for v in data) or any(v != 1 for v in data[:1024]):
                    raise ValueError('Invalid legacy world; migration stopped without changing it')
                # Compare only the documented old flat baseline. Keep original untouched.
                for cz in range(2):
                    for cx in range(2):
                        edits = {}
                        for z in range(16):
                            for x in range(16):
                                for y in range(32):
                                    value = data[(y*32+cz*16+z)*32+cx*16+x]
                                    old = 1 if y == 0 else 2 if y < 7 else 3 if y == 7 else 0
                                    if value != old:
                                        edits[(z*16+x)*HEIGHT+y] = value
                        if edits:
                            self.save((cx, cz), edits)
                self.meta['migrated_legacy'] = True
            atomic_json(metadata, self.meta)

    def path(self, key):
        x, z = key
        if not (-LIMIT <= x < LIMIT and -LIMIT <= z < LIMIT):
            raise ValueError('Chunk outside world bounds')
        return self.root / 'chunks-v1' / f'{x}.{z}.json'

    def load(self, key):
        path = self.path(key)
        if not path.exists():
            return None
        value = json.loads(path.read_text())
        if value.get('chunk') != list(key) or value.get('generator') != 1:
            raise ValueError('Invalid saved chunk identity')
        pairs = value['edits']
        result = {}
        for index, block in pairs:
            if type(index) is not int or type(block) is not int or not 0 <= index < SIZE or not 0 <= block < STATE_COUNT:
                raise ValueError('Invalid chunk edit')
            if index in result or (index % HEIGHT == 0 and block != 1):
                raise ValueError('Duplicate edit or changed bedrock')
            result[index] = block
        return result

    def save(self, key, edits):
        atomic_json(self.path(key), {'generator': 1, 'chunk': list(key), 'edits': sorted(edits.items())})


class Pager:
    def __init__(self, link, store):
        self.link, self.store = link, store
        self.views = {}
        self.loaded = {}
        self.link.command(11, struct.pack('<I', store.meta['seed']))

    def snapshot(self, slot):
        cursor, edits, dirty = 0, {}, False
        while cursor < 4096:
            reply = self.link.command(17, struct.pack('<BH', slot, cursor))
            next_cursor, count, flag = struct.unpack_from('<HBB', reply)
            if not cursor < next_cursor <= 4096 or count > 11:
                raise ValueError('Invalid MCU edit snapshot')
            for i in range(count):
                index, block = struct.unpack_from('<HH', reply, 4+i*4)
                if index >= SIZE or block >= STATE_COUNT or index in edits or (index % HEIGHT == 0 and block != 1):
                    raise ValueError('Invalid MCU edit snapshot state')
                edits[index] = block
            dirty |= bool(flag)
            cursor = next_cursor
        return edits, dirty

    def evict(self, key):
        entry = self.loaded[key]
        edits, dirty = self.snapshot(entry['slot'])
        if dirty:
            self.store.save(key, edits)
            self.link.command(16, bytes([entry['slot']]))
        self.link.command(15, bytes([entry['slot']]))
        del self.loaded[key]

    def view(self, actor, center=None):
        if actor not in (0, 1, 2, 3):
            raise ValueError('Invalid player slot')
        if center is None:
            self.views.pop(actor, None)
        else:
            self.views[actor] = center
        wanted = set()
        for cx, cz in self.views.values():
            wanted.update((x, z) for z in range(cz-2, cz+3) for x in range(cx-2, cx+3)
                          if -LIMIT <= x < LIMIT and -LIMIT <= z < LIMIT)
        for key in list(self.loaded):
            if key not in wanted:
                self.evict(key)
        for key in sorted(wanted - self.loaded.keys()):
            occupied = {e['slot'] for e in self.loaded.values()}
            slot = next(i for i in range(100) if i not in occupied)
            edits = self.store.load(key)
            self.link.command(12, struct.pack('<Bii', slot, *key))
            pairs = list((edits or {}).items())
            for offset in range(0, len(pairs), 11):
                batch = pairs[offset:offset+11]
                payload = bytes([slot, len(batch)]) + b''.join(struct.pack('<HH', *p) for p in batch)
                if not self.link.command(14, payload)[0]:
                    raise ValueError('MCU edit RAM is full while restoring chunks; saved files remain intact')
            self.loaded[key] = {'slot': slot, 'edits': edits or {}}

    def read(self, key):
        if key not in self.loaded:
            raise ValueError('Chunk is not in any active player view')
        slot = self.loaded[key]['slot']
        result = bytearray()
        while len(result) < SIZE * 2:
            response = self.link.command(13, struct.pack('<BH', slot, len(result)//2))
            next_cursor, count = struct.unpack_from('<HB', response)
            if not len(result)//2 < next_cursor <= SIZE or not 1 <= count <= 15:
                raise ValueError('Invalid MCU terrain stream')
            for i in range(count):
                length, value = struct.unpack_from('<BH', response, 3+i*3)
                if not length or value >= STATE_COUNT:
                    raise ValueError('Invalid MCU terrain run')
                result.extend(struct.pack('<H', value)*length)
            if len(result)//2 != next_cursor:
                raise ValueError('MCU terrain stream cursor mismatch')
        return bytes(result)

    def checkpoint_edit(self, response):
        changed = bytearray(response)
        if not response[17]:
            return bytes(changed)
        for key, entry in self.loaded.items():
            slot = entry['slot']
            if not (response[20+slot//8] & (1 << (slot % 8))):
                continue
            edits, dirty = self.snapshot(slot)
            if edits != entry['edits']:
                # Save only affected chunks, including neighboring circuit changes.
                self.store.save(key, edits)
                entry['edits'] = edits
                changed.extend(struct.pack('<ii', *key))
            if dirty:
                self.link.command(16, bytes([slot]))
        return bytes(changed)

    def settle(self):
        return self.checkpoint_edit(self.link.command(27))

    def close(self):
        for key in list(self.loaded):
            self.evict(key)
