'use strict'
const fs = require('node:fs')
const path = require('node:path')
const data = require('minecraft-data')('26.1')
const root = path.resolve(__dirname, '..')
const legacy = require('../host/data/palette.json')
const states = legacy.map(name => ({ name, state: data.blocksByName[name].defaultState }))
const groups = []
const facing = ['north', 'east', 'south', 'west']
function stateId (name, properties) {
  const block = data.blocksByName[name]
  let offset = 0
  for (const field of block.states) {
    const value = properties[field.name]
    const index = field.type === 'bool' ? (value ? 0 : 1) : field.values.indexOf(String(value))
    if (value === undefined || index < 0) throw new Error(`Missing ${name}.${field.name}`)
    offset = offset * field.num_values + index
  }
  return block.minStateId + offset
}
function group (name, kind, count, decode, manual = true) {
  if (!data.blocksByName[name]) return
  const start = states.length
  for (let bits = 0; bits < count; bits++) {
    const properties = decode(bits)
    states.push({ name, properties, state: stateId(name, properties) })
  }
  groups.push({ name, kind, start, count, manual, item: data.itemsByName[name === 'redstone_wire' ? 'redstone' : name]?.id })
}
const woods = 'oak spruce birch jungle acacia dark_oak mangrove cherry pale_oak crimson warped bamboo'.split(' ')
for (const name of [...woods.map(w => w + '_door'), 'iron_door']) group(name, 1, 64, b => ({
  facing: facing[b & 3], open: !!(b & 4), half: b & 8 ? 'upper' : 'lower', hinge: b & 16 ? 'right' : 'left', powered: !!(b & 32)
}), name !== 'iron_door')
for (const name of [...woods.map(w => w + '_trapdoor'), 'iron_trapdoor']) group(name, 2, 32, b => ({
  facing: facing[b & 3], open: !!(b & 4), half: b & 8 ? 'top' : 'bottom', powered: !!(b & 16), waterlogged: false
}), name !== 'iron_trapdoor')
const masonry = ['stone', 'cobblestone', 'stone_brick', 'brick', 'deepslate_brick', 'cobbled_deepslate', 'sandstone', 'quartz']
for (const material of [...woods, ...masonry]) group(material + '_slab', 3, 3, b => ({ type: ['bottom', 'top', 'double'][b], waterlogged: false }))
for (const material of [...woods, ...masonry]) group(material + '_stairs', 4, 40, b => ({
  facing: facing[b & 3], half: b & 4 ? 'top' : 'bottom', shape: ['straight', 'inner_left', 'inner_right', 'outer_left', 'outer_right'][b >> 3], waterlogged: false
}))
group('lever', 5, 24, b => ({ facing: facing[b & 3], face: ['floor', 'wall', 'ceiling'][(b >> 2) % 3], powered: b >= 12 }))
group('redstone_wire', 6, 1296, b => {
  const props = { power: b % 16 }; let connections = Math.floor(b / 16)
  for (const side of facing) { props[side] = ['none', 'side', 'up'][connections % 3]; connections = Math.floor(connections / 3) }
  return props
})
group('redstone_lamp', 7, 2, b => ({ lit: !!b }))
if (states.length >= 65535) throw new Error('State palette exhausted')
const filename = path.join(root, 'host/data/states.json')
if (fs.existsSync(filename)) {
  const old = JSON.parse(fs.readFileSync(filename)).states
  old.forEach((entry, i) => { if (JSON.stringify(entry) !== JSON.stringify(states[i])) throw new Error(`Would reinterpret saved state ${i}`) })
}
fs.writeFileSync(filename, JSON.stringify({ states, groups }) + '\n')
fs.writeFileSync(path.join(root, 'firmware/States.h'), `// Generated by tools/build_states.js. State IDs are append-only.\n#pragma once\n#include <stdint.h>\nstatic constexpr unsigned STATE_COUNT = ${states.length};\nstatic constexpr unsigned REDSTONE_BLOCK = ${legacy.indexOf('redstone_block')};\nstruct BlockGroup { uint16_t start, count; uint8_t kind; bool manual; };\nstatic const BlockGroup GROUPS[] = {\n${groups.map(g => ` {${g.start},${g.count},${g.kind},${g.manual}}, // ${g.name}`).join('\n')}\n};\n`)
console.log(`${states.length} stable states across ${groups.length} functional block types; ${legacy.length} legacy IDs preserved`)
