// Stable, append-only byte palette. Never reorder existing entries in palette.json.
const fs = require('node:fs')
const path = require('node:path')
const data = require('minecraft-data')('26.1')
const colors = 'white orange magenta light_blue yellow lime pink gray light_gray cyan purple blue brown green red black'.split(' ')
const woods = 'oak spruce birch jungle acacia dark_oak mangrove cherry pale_oak crimson warped bamboo'.split(' ')
const names = ['air', 'bedrock', 'dirt', 'grass_block', 'stone']
const add = name => { if (!names.includes(name)) names.push(name) }
for (const name of `cobblestone mossy_cobblestone granite polished_granite diorite polished_diorite andesite polished_andesite
  deepslate cobbled_deepslate polished_deepslate deepslate_bricks cracked_deepslate_bricks deepslate_tiles cracked_deepslate_tiles chiseled_deepslate
  tuff polished_tuff tuff_bricks chiseled_tuff chiseled_tuff_bricks calcite dripstone_block smooth_basalt basalt polished_basalt
  stone_bricks mossy_stone_bricks cracked_stone_bricks chiseled_stone_bricks smooth_stone bricks
  sandstone cut_sandstone chiseled_sandstone smooth_sandstone red_sandstone cut_red_sandstone chiseled_red_sandstone smooth_red_sandstone
  quartz_block quartz_bricks chiseled_quartz_block quartz_pillar smooth_quartz purpur_block purpur_pillar
  blackstone polished_blackstone polished_blackstone_bricks cracked_polished_blackstone_bricks chiseled_polished_blackstone gilded_blackstone
  netherrack nether_bricks red_nether_bricks cracked_nether_bricks chiseled_nether_bricks end_stone end_stone_bricks
  glass tinted_glass glowstone sea_lantern shroomlight obsidian crying_obsidian
  prismarine prismarine_bricks dark_prismarine amethyst_block
  coarse_dirt rooted_dirt mud packed_mud mud_bricks clay sand red_sand gravel snow_block ice packed_ice blue_ice moss_block pale_moss_block
  terracotta resin_block resin_bricks chiseled_resin_bricks sponge wet_sponge
  bookshelf melon pumpkin hay_block bone_block dried_kelp_block honeycomb_block
  soul_sand soul_soil magma_block nether_wart_block warped_wart_block`.trim().split(/\s+/)) add(name)
for (const wood of woods) add(wood + '_planks')
add('bamboo_mosaic')
for (const wood of woods.slice(0, 9)) { add(wood + '_log'); add('stripped_' + wood + '_log') }
for (const wood of ['crimson', 'warped']) { add(wood + '_stem'); add('stripped_' + wood + '_stem') }
for (const family of ['wool', 'stained_glass', 'terracotta', 'concrete', 'concrete_powder']) {
  for (const color of colors) add(color + '_' + family)
}
for (const metal of ['coal', 'iron', 'copper', 'gold', 'lapis', 'redstone', 'emerald', 'diamond']) {
  add(metal + '_block'); add(metal + '_ore'); add('deepslate_' + metal + '_ore')
}
for (const name of ['netherite_block', 'ancient_debris', 'raw_iron_block', 'raw_copper_block', 'raw_gold_block', 'nether_gold_ore', 'nether_quartz_ore']) add(name)
if (names.length > 255) throw new Error(`Palette has ${names.length} entries; 255 is reserved for unsupported items`)
for (const name of names) if (!data.blocksByName[name]) throw new Error(`Unknown block ${name}`)
const filename = path.join(__dirname, '../host/data/palette.json')
if (fs.existsSync(filename)) {
  const previous = JSON.parse(fs.readFileSync(filename))
  previous.forEach((name, id) => { if (names[id] !== name) throw new Error(`Would reinterpret saved palette ID ${id}`) })
}
fs.writeFileSync(filename, JSON.stringify(names, null, 2) + '\n')
fs.writeFileSync(path.join(__dirname, '../firmware/Palette.h'), `// Generated by tools/build_palette.js. IDs are append-only.\n#pragma once\nstatic constexpr unsigned BLOCK_PALETTE_SIZE = ${names.length};\n`)
console.log(`${names.length} palette entries, ${names.length - 1} placeable block types; RAM remains 32768 bytes`)
