// Generated by tools/build_states.js. State IDs are append-only.
#pragma once
#include <stdint.h>
static constexpr unsigned STATE_COUNT = 3685;
static constexpr unsigned REDSTONE_BLOCK = 239;
struct BlockGroup { uint16_t start, count; uint8_t kind; bool manual; };
static const BlockGroup GROUPS[] = {
 {255,64,1,true}, // oak_door
 {319,64,1,true}, // spruce_door
 {383,64,1,true}, // birch_door
 {447,64,1,true}, // jungle_door
 {511,64,1,true}, // acacia_door
 {575,64,1,true}, // dark_oak_door
 {639,64,1,true}, // mangrove_door
 {703,64,1,true}, // cherry_door
 {767,64,1,true}, // pale_oak_door
 {831,64,1,true}, // crimson_door
 {895,64,1,true}, // warped_door
 {959,64,1,true}, // bamboo_door
 {1023,64,1,false}, // iron_door
 {1087,32,2,true}, // oak_trapdoor
 {1119,32,2,true}, // spruce_trapdoor
 {1151,32,2,true}, // birch_trapdoor
 {1183,32,2,true}, // jungle_trapdoor
 {1215,32,2,true}, // acacia_trapdoor
 {1247,32,2,true}, // dark_oak_trapdoor
 {1279,32,2,true}, // mangrove_trapdoor
 {1311,32,2,true}, // cherry_trapdoor
 {1343,32,2,true}, // pale_oak_trapdoor
 {1375,32,2,true}, // crimson_trapdoor
 {1407,32,2,true}, // warped_trapdoor
 {1439,32,2,true}, // bamboo_trapdoor
 {1471,32,2,false}, // iron_trapdoor
 {1503,3,3,true}, // oak_slab
 {1506,3,3,true}, // spruce_slab
 {1509,3,3,true}, // birch_slab
 {1512,3,3,true}, // jungle_slab
 {1515,3,3,true}, // acacia_slab
 {1518,3,3,true}, // dark_oak_slab
 {1521,3,3,true}, // mangrove_slab
 {1524,3,3,true}, // cherry_slab
 {1527,3,3,true}, // pale_oak_slab
 {1530,3,3,true}, // crimson_slab
 {1533,3,3,true}, // warped_slab
 {1536,3,3,true}, // bamboo_slab
 {1539,3,3,true}, // stone_slab
 {1542,3,3,true}, // cobblestone_slab
 {1545,3,3,true}, // stone_brick_slab
 {1548,3,3,true}, // brick_slab
 {1551,3,3,true}, // deepslate_brick_slab
 {1554,3,3,true}, // cobbled_deepslate_slab
 {1557,3,3,true}, // sandstone_slab
 {1560,3,3,true}, // quartz_slab
 {1563,40,4,true}, // oak_stairs
 {1603,40,4,true}, // spruce_stairs
 {1643,40,4,true}, // birch_stairs
 {1683,40,4,true}, // jungle_stairs
 {1723,40,4,true}, // acacia_stairs
 {1763,40,4,true}, // dark_oak_stairs
 {1803,40,4,true}, // mangrove_stairs
 {1843,40,4,true}, // cherry_stairs
 {1883,40,4,true}, // pale_oak_stairs
 {1923,40,4,true}, // crimson_stairs
 {1963,40,4,true}, // warped_stairs
 {2003,40,4,true}, // bamboo_stairs
 {2043,40,4,true}, // stone_stairs
 {2083,40,4,true}, // cobblestone_stairs
 {2123,40,4,true}, // stone_brick_stairs
 {2163,40,4,true}, // brick_stairs
 {2203,40,4,true}, // deepslate_brick_stairs
 {2243,40,4,true}, // cobbled_deepslate_stairs
 {2283,40,4,true}, // sandstone_stairs
 {2323,40,4,true}, // quartz_stairs
 {2363,24,5,true}, // lever
 {2387,1296,6,true}, // redstone_wire
 {3683,2,7,true}, // redstone_lamp
};
